Repository goorm-6zo/front, pull requests merged in 2025-03, with the labels that each got.

#17 [CHORE]: 페이지 라우팅
  src/pages/CommonComponentTest.tsx
  src/pages/NotFound.tsx
  src/pages/admin/AdminDashboard.tsx
  src/pages/admin/ConferenceEdit.tsx
  src/pages/admin/DeviceConnect.tsx
  src/pages/admin/MessageHistory.tsx
  src/pages/admin/MessageSend.tsx
  src/pages/admin/VisitorStatus.tsx
  src/pages/admin/Visitors.tsx
  src/pages/home/Home.tsx
  src/pages/login/Signup.tsx
  src/pages/reserve/Reservation.tsx
  src/pages/reserve/ReservationComplete.tsx
  src/pages/user/ConferenceInfo.tsx
  src/pages/user/FaceRegistration.tsx
  src/pages/user/Profile.tsx
  src/pages/user/UserDashboard.tsx
  src/router.tsx
Labels: 🔨 CHORE

#19 [FEAT]: 얼굴 등록 기능 추가
  src/components/face/FaceDetection.style.ts
  src/components/face/FaceDetection.tsx
  src/pages/face-recognition/FaceRecognition.tsx
  src/pages/user/FaceRegistration.tsx
Labels: ✨ FEAT, ♻️ REFACTOR

#22 [FEAT]: 회원가입 API 연동
  package-lock.json
  package.json
  src/api/login/useSignUp.ts
  src/pages/login/Signup.tsx
  yarn.lock
Labels: ✨ FEAT

#23 [FEAT]: 로그인 API 연동
  src/api/login/.gitkeep
  src/api/login/login.ts
  src/api/login/signup.ts
  src/pages/login/Login.style.ts
  src/pages/login/Login.tsx
  src/pages/login/Signup.tsx
  src/pages/user/UserDashboard.tsx
  yarn.lock
Labels: ✨ FEAT

#31 FEAT: qr코드 기기 연동 api 통신
  src/api/qrcode/qrcode.ts
Labels: ✨ FEAT

#33 Design/29 common component
  src/assets/react.svg
  src/components/common/button/btn/Btn.style.ts
  src/components/common/button/btn/Btn.tsx
  src/components/common/button/ctabtn/CtaBtn.style.ts
  src/components/common/button/ctabtn/CtaBtn.tsx
  src/components/common/button/floatingbtn/FloatingBtn.style.ts
  src/components/common/button/floatingbtn/FloatingBtn.tsx
  src/components/common/button/icnbtn/IcnBtn.style.ts
  src/components/common/button/icnbtn/IcnBtn.tsx
  src/components/common/button/txtbtn/TxtBtn.style.ts
  src/components/common/button/txtbtn/TxtBtn.tsx
  src/components/common/icon/Icon.tsx
  src/styles/lightTheme.ts
Labels: 🎨 DESIGN

#36 [FEAT]: 유저 정보 상태 관리 및 role 기반 페이지 접근 제어
  package.json
  src/components/common/PrivateRoute.tsx
  src/hooks/useUserData.tsx
  src/main.tsx
  src/pages/AuthProvider.tsx
  src/pages/login/Login.tsx
  src/pages/user/UserDashboard.tsx
  src/router.tsx
  src/store/useAuthStore.ts
  yarn.lock
Labels: ✨ FEAT

#40 [FIX]: 유저 데이터 비동기 처리 개선 및 redirection 수정
  src/hooks/useUserData.tsx
  src/pages/login/Login.tsx
  src/store/useAuthStore.ts
Labels: 🐛 FIX

#43 [DESIGN]: 공통 컴포넌트 제작
  package-lock.json
  src/components/common/ani/Ani.style.ts
  src/components/common/ani/Ani.tsx
  src/components/common/badge/Badge.style.ts
  src/components/common/badge/Badge.tsx
  src/components/common/button/img/Img.style.ts
  src/components/common/button/img/Img.tsx
  src/components/common/profile/Profile.style.ts
  src/components/common/profile/Profile.tsx
  src/components/common/table/Table.style.ts
  src/components/common/table/Table.tsx
  src/pages/user/UserDashboard.tsx
  yarn.lock
Labels: 🎨 DESIGN

#44 [DESIGN]: INPUT 컴포넌트 구현
  src/components/common/input/Input.style.ts
  src/components/common/input/Input.tsx
  src/pages/login/Login.tsx
  src/pages/reserve/Reservation.style.ts
  src/pages/reserve/Reservation.tsx
Labels: 🎨 DESIGN

#46 [DESIGN]: TAG 컴포넌트 제작
  src/components/common/tag/Tag.style.ts
  src/components/common/tag/Tag.tsx
  yarn.lock
Labels: 🎨 DESIGN

#48 [FIX]: 로그인 후 관리자/유저 메인 페이지 외 다른 페이지 접근 불가 문제 해결
  src/hooks/useUserData.tsx
  src/pages/login/Login.tsx
Labels: 🐛 FIX

#55 [DESIGN]: Checkbox 컴포넌트 제작
  src/components/common/checkbox/Checkbox.style.ts
  src/components/common/checkbox/Checkbox.tsx
Labels: 🎨 DESIGN

#56 [FEAT]: 예약 페이지 API 통신
  src/api/admin/qrcode/qrcode.ts
  src/api/reserve/createReservation.ts
  src/api/reserve/getConferenceInfo.ts
  src/hooks/.gitkeep
  src/pages/admin/DeviceConnect.tsx
  src/pages/reserve/Reservation.tsx
Labels: ✨ FEAT

#59 ✨ feat: 관리자 dashboard 컨퍼런스 리스트 API 통신
  src/api/admin/conference/getConferences.ts
  src/pages/admin/AdminDashboard.tsx
  src/pages/admin/adminDashboard/AdminDashboard.style.ts
  src/pages/admin/adminDashboard/AdminDashboard.tsx
  src/router.tsx
Labels: ✨ FEAT

#60 [DESIGN]: Header 컴포넌트 제작
  src/components/common/header/Header.style.ts
  src/components/common/header/Header.tsx
  src/components/common/layout/Layout.tsx
Labels: 🎨 DESIGN

#61 [DESIGN]: 웹 공통 컴포넌트 수정
  src/components/common/ani/Ani.style.ts
  src/components/common/ani/Ani.tsx
  src/components/common/badge/Badge.style.ts
  src/components/common/button/img/Img.style.ts
  src/components/common/img/Img.style.ts
  src/components/common/img/Img.tsx
  src/components/common/profile/Profile.style.ts
  src/components/common/profile/Profile.tsx
  src/pages/login/Login.tsx
  src/pages/user/UserDashboard.tsx
Labels: 🎨 DESIGN

#63 [DESIGN]: Checkbox 컴포넌트 ui 및 상호작용 수정
  src/components/common/checkbox/Checkbox.style.ts
  src/components/common/checkbox/Checkbox.tsx
  src/components/common/icon/SuccessIcon.tsx
Labels: 🎨 DESIGN

#67 [DESIGN] ResponsiveLayout 컴포넌트 제작 (반응형 고려)
  src/components/common/footer/Footer.style.ts
  src/components/common/header/Header.style.ts
  src/components/common/layout/Layout.style.ts
  src/components/common/layout/Layout.tsx
  src/components/common/layout/ResponsiveLayout.style.ts
  src/components/common/layout/ResponsiveLayout.tsx
  src/pages/login/Login.tsx
  src/pages/reserve/Reservation.tsx
  src/pages/user/UserDashboard.tsx
  src/styles/breakpoints.ts
  src/styles/globalStyle.css
  src/styles/lightTheme.ts
Labels: 🎨 DESIGN

#76 [DESIGN]: 카드 컴포넌트 분리하여 제작
  src/components/common/button/btn/Btn.style.ts
  src/components/common/card/admin/adminEntryCard/AdminEntryCard.style.ts
  src/components/common/card/admin/adminEntryCard/AdminEntryCard.tsx
  src/components/common/card/admin/adminMessageCard/AdminMessageCard.style.ts
  src/components/common/card/admin/adminMessageCard/AdminMessageCard.tsx
  src/components/common/card/admin/adminSessionCard/AdminSessionCard.style.ts
  src/components/common/card/admin/adminSessionCard/AdminSessionCard.tsx
  src/components/common/card/admin/adminSessionMessageCard/AdminSessionMessageCard.style.ts
  src/components/common/card/admin/adminSessionMessageCard/AdminSessionMessageCard.tsx
  src/components/common/card/profile/Profile.style.ts
  src/components/common/card/profile/Profile.tsx
  src/components/common/card/user/conferenceCard/ConferenceCard.style.ts
  src/components/common/card/user/conferenceCard/ConferenceCard.tsx
  src/components/common/card/user/faceDataCard/FaceDataCard.style.ts
  src/components/common/card/user/faceDataCard/FaceDataCard.tsx
  src/components/common/card/user/personalDataCard/PersonalDataCard.style.ts
  src/components/common/card/user/personalDataCard/PersonalDataCard.tsx
  src/components/common/card/user/reservationCard/ReservationCard.style.ts
  src/components/common/card/user/reservationCard/ReservationCard.tsx
  src/components/common/card/user/sessionCard/SessionCard.style.ts
  src/components/common/card/user/sessionCard/SessionCard.tsx
  src/components/common/img/Img.style.ts
Labels: 🎨 DESIGN

#72 [FEAT]: 얼굴 등록, 인식 공통 로직 분리
  src/components/face/FaceDetection.tsx
  src/hooks/useFaceDetection.ts
  src/pages/face-recognition/FaceRecognition.style.ts
  src/pages/face-recognition/FaceRecognition.tsx
  src/pages/user/FaceRegistration.style.ts
  src/pages/user/FaceRegistration.tsx
  src/utils/face/getFaceDetectionInfo.ts
  src/utils/face/initAndLoad.ts
  src/utils/face/isFaceInBox.ts
Labels: ✨ FEAT, ♻️ REFACTOR

#78 [DESIGN]: UserDashboard, Profile UI 제작
  src/api/reserve/getMyConference.ts
  src/api/reserve/getMySession.ts
  src/components/alert/Alert.style.ts
  src/components/alert/Alert.tsx
  src/components/common/card/user/conferenceCard/ConferenceCard.style.ts
  src/components/common/card/user/conferenceCard/ConferenceCard.tsx
  src/components/common/card/user/sessionCard/SessionCard.tsx
  src/components/common/header/Header.tsx
  src/components/common/icon/Icon.tsx
  src/components/common/icon/LogoIcon.tsx
  src/components/common/icon/index.ts
  src/components/common/icon/types.ts
  src/pages/user/ConferenceInfo.style.ts
  src/pages/user/ConferenceInfo.tsx
  src/pages/user/Profile.style.ts
  src/pages/user/Profile.tsx
  src/pages/user/UserDashboard.style.ts
  src/pages/user/UserDashboard.tsx
Labels: 🎨 DESIGN

#81 [DESIGN]: 예매 페이지 UI 디자인
  src/components/common/button/ctabtn/CtaBtn.style.ts
  src/components/common/button/ctabtn/CtaBtn.tsx
  src/components/common/card/user/reservationCard/ReservationCard.style.ts
  src/components/common/card/user/reservationCard/ReservationCard.tsx
  src/components/common/checkbox/Checkbox.tsx
  src/components/reservation/session/CheckBox.style.ts
  src/components/reservation/session/CheckBox.tsx
  src/components/reservation/session/CheckBoxList.style.ts
  src/components/reservation/session/CheckBoxList.tsx
  src/pages/reserve/Reservation.style.ts
  src/pages/reserve/Reservation.tsx
  src/pages/reserve/ReservationComplete.style.ts
  src/pages/reserve/ReservationComplete.tsx
Labels: ✨ FEAT, 🎨 DESIGN

#82 ✨ feat: 컨퍼런스 정보 get api 변경
  src/api/admin/conference/getConferenceInfo.ts
  src/pages/admin/adminDashboard/AdminDashboard.tsx
Labels: ✨ FEAT

#84 [FIX]: 특정 컨퍼런스 조회 api 호출 로직 수정
  src/api/admin/conference/getConferenceInfo.ts
  src/pages/admin/adminDashboard/AdminDashboard.tsx
Labels: 🐛 FIX

#85 [DESIGN] 관리자 DashBoard UI 디자인
  src/components/common/card/admin/adminSessionCard/AdminSessionCard.style.ts
  src/pages/admin/adminDashboard/AdminDashboard.style.ts
  src/pages/admin/adminDashboard/AdminDashboard.tsx
Labels: 🎨 DESIGN

#88 [STYLE]: 미디어 쿼리 오류 수정
  src/styles/breakpoints.ts
Labels: 🐛 FIX, 💄 STYLE

#89 [FEAT]: 컨퍼런스 카드 컴포넌트 구현 및 입장 현황 페이지 적용
  src/components/common/card/admin/adminEntryCard/AdminEntryCard.style.ts
  src/components/common/card/admin/adminEntryCard/AdminEntryCard.tsx
  src/components/common/icon/Icon.tsx
  src/components/common/icon/RightArrow.tsx
  src/components/common/icon/types.ts
  src/components/common/tag/Tag.style.ts
  src/components/common/tag/Tag.tsx
  src/pages/admin/Visitors.style.ts
  src/pages/admin/Visitors.tsx
  src/styles/globalStyle.css
Labels: ✨ FEAT, 🎨 DESIGN, 💄 STYLE

#93 [FIX]: 미디어 쿼리 수정
  src/components/common/card/admin/adminEntryCard/AdminEntryCard.style.ts
  src/components/common/layout/ResponsiveLayout.style.ts
  src/pages/admin/Visitors.style.ts
  src/pages/admin/adminDashboard/AdminDashboard.style.ts
  src/pages/admin/adminDashboard/AdminDashboard.tsx
  src/styles/breakpoints.ts
  src/styles/lightTheme.ts
Labels: 🐛 FIX, 💄 STYLE

#95 [FEAT]: 로그인 필드 유효성 검사 및 오류 처리
  src/pages/login/Login.style.ts
  src/pages/login/Login.tsx
Labels: ✨ FEAT, 🎨 DESIGN

#99 [FIX]: 로그인 후 유저 데이터 및 컨퍼런스 데이터 처리 오류
  src/api/admin/conference/getConferenceInfo.ts
  src/api/login/login.ts
  src/components/common/card/admin/adminEntryCard/AdminEntryCard.tsx
  src/pages/login/Login.tsx
Labels: 🐛 FIX

#103 [CHORE]: 카드 컴포넌트 디렉토리 경로 수정
  src/components/card/admin/adminEntryCard/AdminEntryCard.style.ts
  src/components/card/admin/adminEntryCard/AdminEntryCard.tsx
  src/components/card/admin/adminMessageCard/AdminMessageCard.style.ts
  src/components/card/admin/adminMessageCard/AdminMessageCard.tsx
  src/components/card/admin/adminSessionCard/AdminSessionCard.style.ts
  src/components/card/admin/adminSessionCard/AdminSessionCard.tsx
  src/components/card/admin/adminSessionMessageCard/AdminSessionMessageCard.style.ts
  src/components/card/admin/adminSessionMessageCard/AdminSessionMessageCard.tsx
  src/components/card/profile/Profile.style.ts
  src/components/card/profile/Profile.tsx
  src/components/card/user/conferenceCard/ConferenceCard.style.ts
  src/components/card/user/conferenceCard/ConferenceCard.tsx
  src/components/card/user/faceDataCard/FaceDataCard.style.ts
  src/components/card/user/faceDataCard/FaceDataCard.tsx
  src/components/card/user/personalDataCard/PersonalDataCard.style.ts
  src/components/card/user/personalDataCard/PersonalDataCard.tsx
  src/components/card/user/reservationCard/ReservationCard.style.ts
  src/components/card/user/reservationCard/ReservationCard.tsx
  src/components/card/user/sessionCard/SessionCard.style.ts
  src/components/card/user/sessionCard/SessionCard.tsx
  src/pages/admin/Visitors.tsx
  src/pages/admin/adminDashboard/AdminDashboard.tsx
Labels: 🔨 CHORE

#105 [DESIGN]: Sheet 컴포넌트 UI 구현 및 Btn 컴포넌트 수정
  src/components/common/button/btn/Btn.style.ts
  src/components/common/button/btn/Btn.tsx
  src/components/common/sheet/Sheet.style.ts
  src/components/common/sheet/Sheet.tsx
  src/components/common/sheet/SheetBtn.style.ts
  src/components/common/sheet/SheetBtn.tsx
Labels: 🎨 DESIGN, 🔨 CHORE

#107 [CHORE]: Card 컴포넌트 Import문 수정
  src/components/reservation/session/CheckBoxList.tsx
  src/pages/user/ConferenceInfo.tsx
  src/pages/user/Profile.tsx
  src/pages/user/UserDashboard.tsx
Labels: 🔨 CHORE

#112 [FEAT]: SSE로 실시간 입장 현황 데이터 연동
  src/api/reserve/getConferenceInfo.ts
  src/components/card/admin/adminEntryCard/AdminEntryCard.style.ts
  src/components/card/admin/adminEntryCard/AdminEntryCard.tsx
  src/components/common/button/floatingbtn/FloatingBtn.style.ts
  src/hooks/useConferenceData.ts
  src/hooks/useSSE.ts
  src/hooks/useUserData.ts
  src/pages/admin/Visitors.style.ts
  src/pages/admin/Visitors.tsx
  src/pages/reserve/Reservation.tsx
Labels: ✨ FEAT

#114 [FEAT]: 얼굴 인식 API 통신
  src/api/face/faceAuthentication.ts
  src/pages/face-recognition/FaceRecognition.tsx
  src/pages/reserve/Reservation.style.ts
Labels: ✨ FEAT

#117 [DESIGN]: 얼굴 입장 UI 디자인
  src/components/common/toast/Toast.style.ts
  src/components/common/toast/Toast.tsx
  src/pages/face-recognition/FaceRecognition.style.ts
  src/pages/face-recognition/FaceRecognition.tsx
Labels: 🎨 DESIGN

#119 [FEAT]: 관리자 dashboard 카드 상세 페이지 api 연동
  src/api/admin/conference/getSessionInfo.ts
  src/components/card/admin/adminSessionCard/AdminSessionCard.style.ts
  src/components/card/admin/adminSessionCard/AdminSessionCard.tsx
  src/pages/admin/AdminConferenceInfo.tsx
  src/pages/admin/ConferenceEdit.tsx
  src/pages/admin/adminDashboard/AdminDashboard.tsx
  src/router.tsx
  src/routes/router.tsx
Labels: ✨ FEAT

#122 [DESIGN]: 관리자 상세 페이지 1차 디자인
  src/api/admin/conference/getSessionInfo.ts
  src/components/common/input/Input.style.ts
  src/components/common/input/Input.tsx
  src/pages/admin/AdminConferenceInfo.style.ts
  src/pages/admin/AdminConferenceInfo.tsx
  src/utils/time/timeFormat.ts
Labels: 🎨 DESIGN

#124 Design/100 icon size custom
  src/assets/svg/IcnFillDelete.tsx
  src/assets/svg/IcnFillEdit.tsx
  src/assets/svg/IcnFillSend.tsx
  src/assets/svg/IcnFillSuccess.tsx
  src/assets/svg/IcnFillWarning.tsx
  src/assets/svg/IcnLogo.tsx
  src/assets/svg/IcnStrokeBottom.tsx
  src/assets/svg/IcnStrokeCheck.tsx
  src/assets/svg/IcnStrokeClose.tsx
  src/assets/svg/IcnStrokeEdit.tsx
  src/assets/svg/IcnStrokeFace.tsx
  src/assets/svg/IcnStrokeLeft.tsx
  src/assets/svg/IcnStrokeMenu.tsx
  src/assets/svg/IcnStrokePlus.tsx
  src/assets/svg/IcnStrokeRight.tsx
  src/assets/svg/IcnStrokeTop.tsx
  src/assets/svg/IcnStrokeWarning.tsx
  src/components/card/admin/adminEntryCard/AdminEntryCard.tsx
  src/components/card/admin/adminSessionCard/AdminSessionCard.tsx
  src/components/card/user/faceDataCard/FaceDataCard.tsx
  src/components/common/button/ctabtn/CtaBtn.tsx
  src/components/common/button/icnbtn/IcnBtn.style.ts
  src/components/common/checkbox/Checkbox.style.ts
  src/components/common/checkbox/Checkbox.tsx
  src/components/common/footer/Footer.style.ts
  src/components/common/footer/Footer.tsx
  src/components/common/header/Header.tsx
  src/components/common/icon/Icon.style.ts
  src/components/common/icon/Icon.tsx
  src/components/common/icon/types.ts
  src/components/common/notify/Notify.tsx
  src/components/common/popup/Popup.tsx
  src/components/common/toast/Toast.tsx
Labels: 🔨 CHORE

#126 [FEAT]:관리자 dashboard 데이터 렌더링, 기기연동 및 비활성화
  src/api/admin/active/setActiveState.ts
  src/api/admin/qrcode/qrcode.ts
  src/components/card/admin/adminSessionCard/AdminSessionCard.style.ts
  src/components/card/admin/adminSessionCard/AdminSessionCard.tsx
  src/components/card/profile/Profile.tsx
  src/components/common/button/btn/Btn.style.ts
  src/components/common/button/btn/Btn.tsx
  src/components/common/img/Img.tsx
  src/components/common/tag/Tag.style.ts
  src/pages/admin/DeviceConnect.style.ts
  src/pages/admin/DeviceConnect.tsx
  src/pages/admin/adminDashboard/AdminDashboard.tsx
Labels: ✨ FEAT, 🎨 DESIGN

#130 [FEAT] 로그아웃 구현
  src/api/login/logout.ts
  src/components/common/sheet/Sheet.tsx
Labels: ✨ FEAT

#133 [CHORE]: ProfileContents 컴포넌트 네이밍으로 변경
  src/components/card/admin/adminMessageCard/AdminMessageCard.tsx
  src/components/card/admin/adminSessionCard/AdminSessionCard.tsx
  src/components/card/admin/adminSessionMessageCard/AdminSessionMessageCard.tsx
  src/components/card/profileContents/ProfileContents.style.ts
  src/components/card/profileContents/ProfileContents.tsx
  src/components/card/user/sessionCard/SessionCard.tsx
Labels: 🔨 CHORE

#136 [DESIGN]: 메시지 카드 컴포넌트 디자인 수정
  src/components/card/admin/adminSessionMessageCard/AdminSessionMessageCard.style.ts
  src/components/card/admin/adminSessionMessageCard/AdminSessionMessageCard.tsx
  src/components/common/tag/Tag.style.ts
Labels: 🎨 DESIGN

#140 [DESIGN]: 예약 완료 페이지 아이콘 추가
  src/api/admin/conference/getConferenceInfo.ts
  src/pages/admin/AdminConferenceInfo.tsx
  src/pages/reserve/Reservation.tsx
  src/pages/reserve/ReservationComplete.style.ts
  src/pages/reserve/ReservationComplete.tsx
Labels: 🎨 DESIGN

#141 [DESIGN] 사용자 얼굴등록 여부에 따른 UI 렌더링 스타일 수정
  src/api/face/faceDelete.ts
  src/components/card/user/faceDataCard/FaceDataCard.style.ts
  src/components/card/user/faceDataCard/FaceDataCard.tsx
  src/components/common/notify/Notify.tsx
  src/pages/user/Profile.tsx
  src/pages/user/UserDashboard.tsx
  src/store/useAuthStore.ts
Labels: 🎨 DESIGN

#143 [FEAT]: 얼굴 등록 API 통신
  src/api/face/faceRegister.ts
  src/components/card/admin/adminSessionCard/AdminSessionCard.tsx
  src/constant/faceMsg.ts
  src/hooks/useFaceDetection.ts
  src/pages/admin/AdminConferenceInfo.style.ts
  src/pages/admin/adminDashboard/AdminDashboard.tsx
  src/pages/face-recognition/FaceRecognition.tsx
  src/pages/reserve/Reservation.tsx
  src/pages/user/FaceRegistration.style.ts
  src/pages/user/FaceRegistration.tsx
Labels: ✨ FEAT, 🎨 DESIGN

#144 [FEAT]: 메시지 전송 페이지 구현
  src/components/card/admin/adminSessionMessageCard/AdminSessionMessageCard.style.ts
  src/components/card/admin/adminSessionMessageCard/AdminSessionMessageCard.tsx
  src/components/common/checkbox/Checkbox.style.ts
  src/components/common/img/Img.style.ts
  src/components/common/input/Input.style.ts
  src/components/common/layout/ResponsiveLayout.style.ts
  src/components/common/notify/Notify.style.ts
  src/components/common/notify/Notify.tsx
  src/hooks/useConferenceData.ts
  src/pages/admin/MessageSend.style.ts
  src/pages/admin/MessageSend.tsx
  src/pages/user/UserDashboard.tsx
Labels: ✨ FEAT, 🎨 DESIGN

#145 [CHORE] Footer 컴포넌트를 포함한 UI에서 스크롤이 가능하게 하기
  src/components/common/layout/ResponsiveLayout.style.ts
  src/components/common/layout/ResponsiveLayout.tsx
  src/pages/login/Signup.style.ts
  src/pages/login/Signup.tsx
Labels: 🎨 DESIGN, 🔨 CHORE

#148 [DESIGN] Admin 페이지 Header에서 Sheet 나오도록 수정
  src/components/common/sheet/Sheet.tsx
  src/pages/admin/MessageSend.style.ts
  src/pages/admin/MessageSend.tsx
  src/pages/admin/Visitors.tsx
  src/pages/admin/adminDashboard/AdminDashboard.tsx
Labels: 🎨 DESIGN

#154 [FIX]: 얼굴 인증 코드 수정
  src/hooks/useFaceDetection.ts
  src/pages/admin/AdminConferenceInfo.tsx
  src/pages/face-recognition/FaceRecognition.tsx
Labels: 🐛 FIX, ♻️ REFACTOR

#157 [FEAT]: 메시지 전송 API 연동
  src/api/admin/message/message.ts
  src/components/common/footer/Footer.style.ts
  src/pages/admin/MessageSend.style.ts
  src/pages/admin/MessageSend.tsx
Labels: ✨ FEAT

#159 [CHORE]: Oauth를 이용한 로그인을 위한 authorization UI를 분리합니다.
  src/pages/login/authorization/Authorization.style.ts
  src/pages/login/authorization/Authorization.tsx
  src/pages/login/authorization/AuthorizationCallback.style.ts
  src/pages/login/authorization/AuthorizationCallback.tsx
  src/pages/login/authorization/AuthorizationForm.style.ts
  src/pages/login/authorization/AuthorizationForm.tsx
  src/routes/router.tsx
Labels: 🔨 CHORE

#161 [CHORE]: oauth로그인과 일반 회원가입 authorization 코드 분리
  src/pages/login/authorization/Authorization.tsx
  src/pages/login/authorization/AuthorizationCallback.style.ts
  src/pages/login/authorization/AuthorizationCallback.tsx
  src/pages/login/authorization/AuthorizationForm.style.ts
  src/pages/login/authorization/AuthorizationForm.tsx
  src/router.tsx
  src/routes/router.tsx
Labels: 🐛 FIX, 🔨 CHORE

#163 [STYLE]: 모바일뷰 스타일 점검 및 수정
  src/components/card/user/faceDataCard/FaceDataCard.style.ts
  src/components/card/user/faceDataCard/FaceDataCard.tsx
  src/components/common/sheet/Sheet.tsx
  src/components/common/sheet/SheetBtn.style.ts
Labels: 💄 STYLE

#167 [FIX]: signup-link api 호출로 변경
  src/api/login/signup.ts
Labels: 🐛 FIX

#168 [CHORE]: 주석 삭제
  src/pages/face-recognition/FaceRecognition.tsx
Labels: 💄 STYLE

#174 [DESIGN]: Loading 화면 구현
  src/assets/images/loading.gif
  src/components/common/loading/Loading.style.ts
  src/components/common/loading/Loading.tsx
  src/pages/AuthProvider.tsx
  src/pages/admin/MessageSend.tsx
  src/pages/face-recognition/FaceRecognition.tsx
  src/pages/login/Login.tsx
  src/pages/user/FaceRegistration.tsx
Labels: 🎨 DESIGN

#177 [FIX]: loaing 버그 수정 및 gif 경로 수정
  public/images/loading.gif
  src/components/common/loading/Loading.tsx
  src/hooks/useFaceDetection.ts
Labels: 🐛 FIX

#178 [FIX]: 관리자 페이지 헤더에 메뉴 추가
  src/components/common/header/Header.tsx
  src/components/common/icon/Icon.style.ts
  src/components/common/layout/ResponsiveLayout.style.ts
  src/pages/admin/AdminConferenceInfo.tsx
  src/pages/admin/DeviceConnect.tsx
  src/pages/admin/MessageSend.tsx
  src/pages/admin/VisitorStatus.tsx
  src/pages/admin/Visitors.style.ts
Labels: 🐛 FIX

#180 [FIX]: 메모리 누수를 방지하기 위해 SSE 연결 개선
  src/hooks/useSSE.ts
Labels: 🐛 FIX

#183 [FIX]: 배포 오류 해결
  src/pages/user/FaceRegistration.tsx
Labels: 🐛 FIX

#186 [FIX]: 얼굴 삭제 후 유저 데이터 자동 갱신
  src/api/face/faceDelete.ts
  src/components/card/admin/adminSessionCard/AdminSessionCard.style.ts
  src/components/card/user/faceDataCard/FaceDataCard.tsx
  src/components/common/button/btn/Btn.style.ts
  src/components/common/button/icnbtn/IcnBtn.style.ts
  src/components/common/header/Header.tsx
  src/components/common/icon/Icon.style.ts
  src/components/common/layout/ResponsiveLayout.style.ts
  src/components/common/notify/Notify.style.ts
  src/components/common/table/Table.style.ts
  src/hooks/useUserData.ts
  src/pages/admin/VisitorStatus.style.ts
  src/pages/admin/VisitorStatus.tsx
  src/pages/admin/Visitors.style.ts
  src/pages/user/FaceRegistration.tsx
  src/pages/user/Profile.style.ts
Labels: 🐛 FIX, 💄 STYLE

#189 [DESIGN]: 얼굴 인식 박스 UI 수정
  src/components/card/user/conferenceCard/ConferenceCard.tsx
  src/pages/face-recognition/FaceRecognition.style.ts
  src/pages/face-recognition/FaceRecognition.tsx
  src/pages/user/FaceRegistration.style.ts
  src/pages/user/FaceRegistration.tsx
Labels: 🎨 DESIGN

#190 [FIX: linkUserReservation API 연결 추가하고 본인인증 onSubmit에 API 호출하기
  src/api/authorization/linkUserReservation.ts
  src/pages/login/authorization/AuthorizationCallback.tsx
Labels: 🐛 FIX

#192 [FIX]: user oauth 로그인 시에 예약 연동되도록 API 수정
  src/api/authorization/linkUserReservation.ts
  src/routes/PrivateRoute.tsx
Labels: 🐛 FIX

#194 [FIX]: 디버깅 코드 추가
  src/pages/login/authorization/AuthorizationCallback.tsx
Labels: 🐛 FIX

#200 [DESIGN]: 세션 스피커 이미지 설정
  src/components/card/admin/adminSessionCard/AdminSessionCard.tsx
  src/components/card/admin/adminSessionMessageCard/AdminSessionMessageCard.tsx
  src/components/card/profileContents/ProfileContents.tsx
  src/components/card/user/conferenceCard/ConferenceCard.tsx
  src/components/common/profile/Profile.tsx
  src/pages/admin/AdminConferenceInfo.tsx
  src/pages/admin/MessageSend.tsx
  src/pages/admin/adminDashboard/AdminDashboard.tsx
Labels: 🎨 DESIGN

#202 [DESIGN]: 팝업 오버레이 수정
  src/components/common/popup/Popup.style.ts
Labels: 🎨 DESIGN

#206 [FIX]: SSE 연결 해제 로직 수정 및 unsubscribe API 반영
  src/api/sse/unsubscribe.ts
  src/hooks/useSSE.ts
Labels: 🐛 FIX

#208 [FIX]: 예매 페이지 말줄임표 추가
  src/components/card/user/reservationCard/ReservationCard.style.ts
Labels: 🐛 FIX, 🎨 DESIGN
